name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
    - name: Lint files
      run: yarn lint
